
trigger:
- main

jobs:
- job: 'build'
  displayName: 'build-python'
  continueOnError: false
  pool:
    name: 'Runner-01'

  steps:
  - script: |
      python3 -m pip install --upgrade pip
      pip3 install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      pip3 install pytest pytest-azurepipelines
      pytest
    displayName: 'pytest'
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)/*'
      includeRootFolder: true
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/'
      artifact: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      publishLocation: 'pipeline'


    

