
trigger:
- main

jobs:
- job: 'build'
  displayName: 'build-python'
  continueOnError: false
  pool:
    name: 'Runner-01'

  steps:
  - script: |
      python3 -m pip install --upgrade pip
      pip3 install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      pip3 install pytest pytest-azurepipelines
      pytest
    displayName: 'pytest'


